DATABASE_URL = "postgresql://postgres.ldunpssoxvifemoyeuac:SIHCLI-POTER123*@aws-1-us-east-2.pooler.supabase.com:6543/postgres"
# --------------------------------------------------------
# DEJA AL MENOS 2 LÍNEAS EN BLANCO AQUÍ
# --------------------------------------------------------


# --- SECCIÓN IRI (NUEVA) ---
# ¡IMPORTANTE! El corchete [ debe estar pegado a la izquierda.
[iri]
username = "omejiariv"
password = "k2xpfeNLBW"